#
#   默认任务模板
#
id-1: #这个键值为任务的id，可以为字母数字等组合，必须唯一
  name: 测试用的每日任务  #任务的名字
  display: 1 #任务展示的GUI方块id
  task-type: day #任务的类型: day每日任务,每天都可以接取完成一次,month:每个月可以接取完成一次,once:一次性任务，能被接取完成一次
  auto-get: true #是否自动接取任务,如果为false则不会自动接取任务，为true则会自动接取(需要玩家有权限)
  permission: null #接取任务需要的权限，无需权限则为null
  tasks:     #任务的子任务列表
    - break 1 64
    - fish 64
    - get 126 10
    - kill pig 1
    - task id-2 #引入id-2的所有子任务
  reward:    #任务达成的奖励列表
    - command /kill %player%
    - item 1 61