# 豆腐每日任务系统插件 V1.0.0
# 欢迎使用~~~~

#插件的版本，这个设置一般自己不需要修改(修改可能会导致一些问题)
version: 1.0.0

#每日任务的小任务个数 (1-9)，注意要小于等于当前配置文件中总共的任务数
tasks: 3

#每日任务的小任务可以允许更换的次数，为-1则小任务可以更换无限次,此项无效，暂未在当前版本被支持
change-times: 3

#每日任务的完成奖励,可以使用%player%代表玩家名
#一行一个奖励指令，指令由服务器命令行执行(算是一个OP权限执行?)
#指令不需要带/,更改此项过后请自行检查能否正常执行，这些指令在执行前都未经插件检查
rewards:
  - give %player% 1 64
  - give %player% 3 64
# 每日任务的展现信息
rewards-lore:
  - 泥土 * 64
  - 石头 * 64

#在完成任务之后是否自动替玩家领取奖励(奖励物品溢出背包会导致奖励物品掉落至地上)
auto-rewards: true

#是否开启mysql数据库支持,true: 开启,false(默认): 关闭
mysql: false
#mysql设置，当开启数据库支持时生效
#数据库地址
mysql-host: 127.0.0.1:3306
#数据库名称
mysql-database: database_name
#连接数据库的用户名
mysql-username: root
#连接数据库的密码
mysql-password: 123456