name: TofuDailyTask
version: '${project.version}'
main: cn.ricetofu.task.TofuDailyTask
authors: [ RiceTofu123 ]
description: 豆腐每日任务插件
website: www.ricetofu.cn
commands:
  task:
    description: 玩家默认指令，打开一个显示任务的GUI窗口
    usage: /task

